version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Pre-build stage...
      - echo Checking for any code issues...
      - pylint app.py

  build:
    commands:
      - echo Build started on `date`
      - echo Running tests (if any)...
      # Include any test commands here (optional)
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Build completed successfully!
      - echo Preparing to push artifacts...
      - zip -r deployment-package.zip .
      - aws s3 cp deployment-package.zip s3://your-s3-bucket-name/

artifacts:
  files:
    - deployment-package.zip
