version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing system dependencies...
      - sudo apt-get update -y
      - sudo apt-get install -y python3-pip
      - pip3 install virtualenv
      - virtualenv venv
      - source venv/bin/activate
      - echo Installing Python dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Pre-build step...
      - python -m unittest discover  # Optional: Run tests before the build

  build:
    commands:
      - echo Build step...
      - echo Build completed!

  post_build:
    commands:
      - echo Build successful!
