version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Pre-build stage..."
      - echo "Checking for syntax issues in app.py..."
      - python3 -m py_compile app.py || { echo "Syntax error in app.py"; exit 1; }

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Running tests (if any)..."
      # Include any test commands here (optional)
      - echo "Build completed on `date`"

  post_build:
    commands:
      - echo "Build completed successfully!"
      - echo "No artifacts to store or upload."

